---
- hosts: twist-nuc twist-tplink
  tasks:
  - name: set home
    set_fact:
      home_dir: "{{ lookup('env', 'HOME') }}"
  - name: archive file
    local_action: command tar -C "{{ home_dir }}/ansible" -czf /tmp/files.bzip pop-ping.py pop-recv.py poprow_setup_interface.py setup-devices.sh setup-interfaces.sh setup-olsr.sh etchosts
  - unarchive:
      src: "/tmp/files.bzip"
      dest: "{{ ansible_env.HOME }}/"
- include: copy-etchosts-nuc.yaml
- include: copy-etchosts-tplink.yaml
