#!/usr/bin/env bash

source setenv.sh

if [ $# -ge 1 ]; then
	playbook=$1
	if [ $# -ge 2 ]; then
		shift
		args="--extra-vars \"$@\""
	fi
else
	playbook=echo-hostname.yaml
	args=""
fi

ANSIBLE_FOLDER=${HOME_FOLDER}/ansible/

ssh -A -F ${CONFIG_FILE} ${MASTER_NODE} "cd ${ANSIBLE_FOLDER} && ./install-ansible.sh && ansible-playbook $playbook $args"
