---
- hosts: "{{ testbed | default('twist') }}"
  tasks:
  - name: set nodes string
    set_fact:
      metrics: ""
  - name: deploy constant metrics
    command: "/usr/bin/env sh set_constant_metrics.sh {{ testbed }} {{ metrics }}"
    args:
      chdir: "{{ ansible_env.HOME }}"


