---
- hosts: "{{ testbed | default('twist') }}"
  tasks:
  - name: set prince configuration
    set_fact:
      prince_conf: "prince_conf_c_h.conf"
  - name: set prince log file
    set_fact:
      prince_log: "/tmp/prince.log"
  - name: set hello multiplier
    set_fact:
      hellomult: 10
  - name: set tc multiplier
    set_fact:
      tcmult: 60
  - name: start prince
    command: "/usr/bin/env sh start-prince.sh {{ hellomult }} {{ tcmult }} {{ prince_conf }} {{ prince_log }}"
    args:
      chdir: "{{ ansible_env.HOME }}"
