#!/usr/bin/env sh

if [ $# -ne 5 ]; then
	echo "Usage $0 <start time (unix seconds)> <stop time (unix seconds)> <interval (ms)> <prefix> <olsr version (1 or 2)>"
	exit 1
fi

opkg_path=`which opkg`
if [ -z "$opkg_path" ]; then
	host_name=`hostname | cut -d'.' -f 1`
else
	host_name=`uci get system.@system[0].hostname`
fi

version=$5

if [ $version -eq 2 ]; then
	olsr_pid=`pidof olsrd2_dynamic`
else
	olsr_pid=`pidof olsrd`
fi

prince_pid=`pidof prince`

if [ -z "$prince_pid" ]; then
	prince_pid="0"
fi

echo topology_dumper $1 $2 $3 $4_$host_name $olsr_pid $prince_pid $version | at now
